import React from "react";
import { SystemSettings } from "@/lib/settings";

export interface ReportKpiCard {
  label: string;
  value: string;
  sub?: string;
}

export interface PrintableReportShellProps {
  settings: SystemSettings;
  reportTitle: string;
  subtitle?: string;
  periodLabel: string;
  reportRef?: string;
  generatedBy?: string;
  generatedDate?: string;
  kpiCards?: ReportKpiCard[];
  contentHtml?: string;
  children?: React.ReactNode;
  preparedByLabel?: string;
  preparedByName?: string;
  reviewedByLabel?: string;
  reviewedByName?: string;
  approvedByLabel?: string;
  approvedByName?: string;
  complianceNotice?: string;
}

/**
 * Returns raw HTML string for iframe printing sandbox.
 * Guarantees 100% white canvas, carbon typography, hairline borders, and zero dark-mode leakage.
 */
export function generateReportShellHtml(props: PrintableReportShellProps): string {
  const {
    settings,
    reportTitle,
    subtitle,
    periodLabel,
    reportRef,
    generatedBy = "Authorized System Administrator",
    generatedDate = new Date().toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    }),
    kpiCards = [],
    contentHtml = "",
    preparedByLabel = "Prepared By",
    preparedByName = generatedBy,
    reviewedByLabel = "Reviewed By (Finance / Auditor)",
    reviewedByName = "Internal Audit / Branch Mgr",
    approvedByLabel = "Approved By (General Manager)",
    approvedByName = "Managing Director / Owner",
    complianceNotice = "This document is an official, confidential internal operational & financial report generated by the Enterprise Management System. All recorded values are subject to verification under Philippine statutory tax laws and internal accounting standards."
  } = props;

  const brandName = settings.appName || "Versiklo";
  const shopDesc =
    settings.shopDescription === "Shop Floor"
      ? "MOTORCYCLE PARTS & SERVICES"
      : (settings.shopDescription || "Motorcycle Parts & Services");
  const shopAddr =
    settings.shopAddress || "123 Rizal Ave, Brgy. San Antonio, Pasig City, Metro Manila";
  const shopTin = settings.shopTin || "491-002-884-000 NV";
  const contactPhone = settings.contactPhone || "+63 (02) 8123-4567";
  const contactEmail = settings.contactEmail || "compliance@versiklo.ph";

  const kpiCardsHtml =
    kpiCards.length > 0
      ? `
      <!-- Section 3: Summary Metric Cards -->
      <div style="display: grid; grid-template-columns: repeat(${Math.min(
        kpiCards.length,
        4
      )}, 1fr); gap: 8px; margin: 12px 0;">
        ${kpiCards
          .map(
            (c) => `
          <div style="border: 1px solid #e4e4e7; background-color: #fafafa; padding: 6px 10px; border-radius: 4px;">
            <div style="font-size: 7pt; font-weight: 700; text-transform: uppercase; color: #52525b; letter-spacing: 0.5px;">${c.label}</div>
            <div style="font-size: 13pt; font-weight: 900; font-family: monospace; color: #09090b; margin: 2px 0;">${c.value}</div>
            ${c.sub ? `<div style="font-size: 6.5pt; color: #71717a;">${c.sub}</div>` : ""}
          </div>
        `
          )
          .join("")}
      </div>
    `
      : "";

  return `
    <div style="padding: 12px; max-width: 100%; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #09090b; background-color: #ffffff;">
      
      <!-- Section 1: Dynamic App Brand Header -->
      <div style="display: flex; justify-content: space-between; align-items: flex-start; padding-bottom: 10px; border-bottom: 1px solid #e4e4e7;">
        <div>
          <h1 style="font-size: 15pt; font-weight: 900; text-transform: uppercase; margin: 0; letter-spacing: -0.5px; color: #09090b;">
            ${brandName}
          </h1>
          <p style="font-size: 8pt; font-weight: 700; color: #52525b; text-transform: uppercase; margin: 2px 0 3px 0; letter-spacing: 0.5px;">
            ${shopDesc}
          </p>
          <p style="font-size: 7.5pt; color: #52525b; margin: 1px 0;">${shopAddr}</p>
          <p style="font-size: 7.5pt; color: #71717a; font-family: monospace; margin: 1px 0;">
            BIR Registered TIN: <strong style="color: #09090b;">${shopTin}</strong>
          </p>
          <p style="font-size: 7.5pt; color: #71717a; font-family: monospace; margin: 1px 0;">
            Tel: ${contactPhone} • Email: ${contactEmail}
          </p>
        </div>
        
        <div style="text-align: right; max-width: 300px;">
          <span style="font-size: 7pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #71717a; display: block;">
            OFFICIAL REPORT DOCUMENT
          </span>
          <span style="font-size: 13pt; font-weight: 900; text-transform: uppercase; color: #09090b; display: block; margin: 2px 0;">
            ${reportTitle}
          </span>
          ${subtitle ? `<div style="font-size: 7.5pt; color: #52525b; margin-bottom: 3px;">${subtitle}</div>` : ""}
          ${reportRef ? `<div style="font-size: 7.5pt; font-family: monospace; color: #71717a;">Ref: <strong style="color: #09090b;">${reportRef}</strong></div>` : ""}
          <div style="font-size: 8pt; font-family: monospace; color: #09090b; font-weight: 700; margin-top: 2px;">
            Period: ${periodLabel}
          </div>
        </div>
      </div>

      <!-- Section 2: Document Meta Ribbon -->
      <div style="display: flex; justify-content: space-between; align-items: center; background-color: #f4f4f5; border: 1px solid #e4e4e7; border-top: none; padding: 4px 8px; font-size: 7pt; color: #52525b; font-family: monospace;">
        <div>
          <span>GENERATED BY:</span> <strong style="color: #09090b;">${generatedBy}</strong>
        </div>
        <div>
          <span>ISSUED:</span> <strong style="color: #09090b;">${generatedDate}</strong>
        </div>
        <div>
          <span style="background-color: #ffffff; border: 1px solid #d4d4d8; padding: 1px 6px; border-radius: 3px; font-weight: 700; color: #09090b;">
            OFFICIAL AUDITED COPY
          </span>
        </div>
      </div>

      ${kpiCardsHtml}

      <!-- Section 4: Itemized Data Content / Tables -->
      <div style="margin-top: 10px; width: 100%;">
        ${contentHtml}
      </div>

      <!-- Section 5: Official Certification Signatures -->
      <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-top: 24px; padding-top: 12px; page-break-inside: avoid; break-inside: avoid;">
        <div>
          <div style="font-size: 7pt; font-weight: 700; text-transform: uppercase; color: #52525b; margin-bottom: 24px;">
            ${preparedByLabel}:
          </div>
          <div style="border-top: 1px solid #09090b; width: 90%; margin-bottom: 3px;"></div>
          <div style="font-size: 7.5pt; font-weight: 700; color: #09090b;">${preparedByName}</div>
          <div style="font-size: 6.5pt; color: #71717a;">Authorized Signatory / Date</div>
        </div>

        <div>
          <div style="font-size: 7pt; font-weight: 700; text-transform: uppercase; color: #52525b; margin-bottom: 24px;">
            ${reviewedByLabel}:
          </div>
          <div style="border-top: 1px solid #09090b; width: 90%; margin-bottom: 3px;"></div>
          <div style="font-size: 7.5pt; font-weight: 700; color: #09090b;">${reviewedByName}</div>
          <div style="font-size: 6.5pt; color: #71717a;">Operations Verification / Date</div>
        </div>

        <div>
          <div style="font-size: 7pt; font-weight: 700; text-transform: uppercase; color: #52525b; margin-bottom: 24px;">
            ${approvedByLabel}:
          </div>
          <div style="border-top: 1px solid #09090b; width: 90%; margin-bottom: 3px;"></div>
          <div style="font-size: 7.5pt; font-weight: 700; color: #09090b;">${approvedByName}</div>
          <div style="font-size: 6.5pt; color: #71717a;">Shop Director / Final Approval</div>
        </div>
      </div>

      <!-- Compliance & Watermark Footer -->
      <div style="margin-top: 16px; padding-top: 6px; border-top: 1px solid #e4e4e7; font-size: 6.5pt; color: #71717a; display: flex; justify-content: space-between; align-items: center; page-break-inside: avoid; break-inside: avoid;">
        <div style="max-width: 75%;">
          ${complianceNotice}
        </div>
        <div style="text-align: right; font-family: monospace;">
          <span>${brandName} Engine v2.4 • Confidential</span>
        </div>
      </div>

    </div>
  `;
}

/**
 * Standard React Component counterpart for native Ctrl+P printing containers.
 */
export function PrintableReportLayout(props: PrintableReportShellProps) {
  const {
    settings,
    reportTitle,
    subtitle,
    periodLabel,
    reportRef,
    generatedBy = "Authorized System Administrator",
    generatedDate = new Date().toLocaleString(),
    kpiCards = [],
    children,
    preparedByLabel = "Prepared By",
    preparedByName = generatedBy,
    reviewedByLabel = "Reviewed By (Finance / Auditor)",
    reviewedByName = "Internal Audit / Branch Mgr",
    approvedByLabel = "Approved By (General Manager)",
    approvedByName = "Managing Director / Owner",
    complianceNotice = "This document is an official, confidential internal operational & financial report generated by the Enterprise Management System. All recorded values are subject to verification under Philippine statutory tax laws and internal accounting standards."
  } = props;

  const brandName = settings.appName || "Versiklo";
  const shopDesc =
    settings.shopDescription === "Shop Floor"
      ? "MOTORCYCLE PARTS & SERVICES"
      : (settings.shopDescription || "Motorcycle Parts & Services");
  const shopAddr =
    settings.shopAddress || "123 Rizal Ave, Brgy. San Antonio, Pasig City, Metro Manila";
  const shopTin = settings.shopTin || "491-002-884-000 NV";
  const contactPhone = settings.contactPhone || "+63 (02) 8123-4567";
  const contactEmail = settings.contactEmail || "compliance@versiklo.ph";

  return (
    <div
      data-printable-document="true"
      className="printable-report-document w-full bg-white text-zinc-950 p-4 font-sans text-xs leading-tight"
      style={{ backgroundColor: "#ffffff", color: "#09090b" }}
    >
      {/* Brand Header */}
      <div className="flex justify-between items-start pb-3 border-b border-zinc-200">
        <div>
          <h1 className="text-xl font-black uppercase tracking-tight text-zinc-950 m-0">
            {brandName}
          </h1>
          <p className="text-[10px] font-bold text-zinc-600 uppercase tracking-wider my-0.5">
            {shopDesc}
          </p>
          <p className="text-[9px] text-zinc-600 my-0.5">{shopAddr}</p>
          <p className="text-[9px] text-zinc-500 font-mono my-0.5">
            BIR Registered TIN: <strong className="text-zinc-950">{shopTin}</strong>
          </p>
          <p className="text-[9px] text-zinc-500 font-mono my-0.5">
            Tel: {contactPhone} • Email: {contactEmail}
          </p>
        </div>

        <div className="text-right max-w-xs">
          <span className="text-[9px] font-bold uppercase tracking-wider text-zinc-500 block">
            OFFICIAL REPORT DOCUMENT
          </span>
          <span className="text-base font-black uppercase text-zinc-950 block my-0.5">
            {reportTitle}
          </span>
          {subtitle && <div className="text-[9px] text-zinc-600 mb-1">{subtitle}</div>}
          {reportRef && (
            <div className="text-[9px] font-mono text-zinc-500">
              Ref: <strong className="text-zinc-950">{reportRef}</strong>
            </div>
          )}
          <div className="text-[10px] font-mono font-bold text-zinc-950 mt-1">
            Period: {periodLabel}
          </div>
        </div>
      </div>

      {/* Meta Ribbon */}
      <div className="flex justify-between items-center bg-zinc-100 border-x border-b border-zinc-200 px-3 py-1 text-[9px] text-zinc-600 font-mono">
        <div>
          <span>GENERATED BY:</span> <strong className="text-zinc-950">{generatedBy}</strong>
        </div>
        <div>
          <span>ISSUED:</span> <strong className="text-zinc-950">{generatedDate}</strong>
        </div>
        <div>
          <span className="bg-white border border-zinc-300 px-2 py-0.5 rounded text-[8px] font-bold text-zinc-950 uppercase">
            OFFICIAL AUDITED COPY
          </span>
        </div>
      </div>

      {/* KPI Cards */}
      {kpiCards.length > 0 && (
        <div
          className={`grid gap-2 my-3 ${
            kpiCards.length === 2
              ? "grid-cols-2"
              : kpiCards.length === 3
              ? "grid-cols-3"
              : "grid-cols-4"
          }`}
        >
          {kpiCards.map((card, i) => (
            <div
              key={i}
              className="border border-zinc-200 bg-zinc-50 p-2 rounded"
            >
              <div className="text-[8px] font-bold uppercase text-zinc-600 tracking-wider">
                {card.label}
              </div>
              <div className="text-sm font-black font-mono text-zinc-950 my-0.5">
                {card.value}
              </div>
              {card.sub && <div className="text-[8px] text-zinc-500">{card.sub}</div>}
            </div>
          ))}
        </div>
      )}

      {/* Main Content */}
      <div className="mt-3 w-full">{children}</div>

      {/* Signatures */}
      <div className="grid grid-cols-3 gap-4 mt-6 pt-3 border-t border-zinc-200 break-inside-avoid">
        <div>
          <div className="text-[8px] font-bold uppercase text-zinc-600 mb-6">
            {preparedByLabel}:
          </div>
          <div className="border-t border-zinc-900 w-11/12 mb-1" />
          <div className="text-[9px] font-bold text-zinc-950">{preparedByName}</div>
          <div className="text-[8px] text-zinc-500">Authorized Signatory / Date</div>
        </div>

        <div>
          <div className="text-[8px] font-bold uppercase text-zinc-600 mb-6">
            {reviewedByLabel}:
          </div>
          <div className="border-t border-zinc-900 w-11/12 mb-1" />
          <div className="text-[9px] font-bold text-zinc-950">{reviewedByName}</div>
          <div className="text-[8px] text-zinc-500">Operations Verification / Date</div>
        </div>

        <div>
          <div className="text-[8px] font-bold uppercase text-zinc-600 mb-6">
            {approvedByLabel}:
          </div>
          <div className="border-t border-zinc-900 w-11/12 mb-1" />
          <div className="text-[9px] font-bold text-zinc-950">{approvedByName}</div>
          <div className="text-[8px] text-zinc-500">Shop Director / Final Approval</div>
        </div>
      </div>

      {/* Compliance Footer */}
      <div className="mt-4 pt-2 border-t border-zinc-200 text-[8px] text-zinc-500 flex justify-between items-center break-inside-avoid">
        <div className="max-w-[75%]">{complianceNotice}</div>
        <div className="text-right font-mono">
          <span>{brandName} Engine v2.4 • Confidential</span>
        </div>
      </div>
    </div>
  );
}
