import { printIsolatedDocument } from "./printUtils";

/**
 * Escapes a single CSV cell according to RFC 4180:
 * - Null/undefined becomes empty string
 * - If value contains comma, double-quote, or newline, it is wrapped in double quotes
 * - Internal double quotes are escaped as two double quotes ("")
 */
export function escapeCsvField(val: string | number | null | undefined): string {
  if (val === null || val === undefined) return "";
  const str = String(val);
  if (/[",\r\n]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Downloads a generated CSV string in the browser with UTF-8 BOM to guarantee
 * proper encoding of currency symbols (₱), accents, and em-dashes across Microsoft Excel, LibreOffice, and Google Sheets.
 */
export function downloadCsvFile(filename: string, csvContent: string): void {
  if (typeof window === "undefined") return;

  // Prepend UTF-8 Byte Order Mark (\uFEFF) to prevent CP1252/ANSI mojibake in Windows Excel
  const bom = "\uFEFF";
  const blob = new Blob([bom + csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename.endsWith(".csv") ? filename : `${filename}.csv`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  setTimeout(() => {
    URL.revokeObjectURL(url);
  }, 1000);
}

export interface ReportCsvHeaderConfig {
  appName: string;
  shopDescription?: string;
  shopAddress?: string;
  shopTin?: string;
  reportTitle: string;
  periodLabel: string;
  generatedBy?: string;
  generatedDate?: string;
}

export interface ReportCsvData {
  headers: string[];
  rows: (string | number | null | undefined)[][];
  summaryRows?: (string | number | null | undefined)[][];
}

/**
 * Builds a standardized RFC 4180 CSV document incorporating official enterprise metadata headers,
 * followed by the structured data grid and optional summary footer rows.
 */
export function buildEnterpriseReportCsv(
  config: ReportCsvHeaderConfig,
  data: ReportCsvData
): string {
  const lines: string[] = [];

  // 1. Company Letterhead Metadata
  lines.push([escapeCsvField(config.appName.toUpperCase()), escapeCsvField(config.shopDescription || "")].join(","));
  if (config.shopAddress) {
    lines.push([escapeCsvField("Address:"), escapeCsvField(config.shopAddress)].join(","));
  }
  if (config.shopTin) {
    lines.push([escapeCsvField("TIN:"), escapeCsvField(config.shopTin)].join(","));
  }
  lines.push("");

  // 2. Report Details
  lines.push([escapeCsvField("REPORT:"), escapeCsvField(config.reportTitle)].join(","));
  lines.push([escapeCsvField("PERIOD:"), escapeCsvField(config.periodLabel)].join(","));
  lines.push([escapeCsvField("GENERATED BY:"), escapeCsvField(config.generatedBy || "Authorized Staff")].join(","));
  lines.push([escapeCsvField("DATE ISSUED:"), escapeCsvField(config.generatedDate || new Date().toLocaleString())].join(","));
  lines.push("");

  // 3. Table Column Headers
  lines.push(data.headers.map(escapeCsvField).join(","));

  // 4. Data Rows
  for (const row of data.rows) {
    lines.push(row.map(escapeCsvField).join(","));
  }

  // 5. Summary Rows
  if (data.summaryRows && data.summaryRows.length > 0) {
    lines.push("");
    lines.push([escapeCsvField("--- SUMMARY TOTALS ---")].join(","));
    for (const sumRow of data.summaryRows) {
      lines.push(sumRow.map(escapeCsvField).join(","));
    }
  }

  // 6. Certification Disclaimer
  lines.push("");
  lines.push([escapeCsvField("CONFIDENTIALITY:"), escapeCsvField("Official record generated by system. For internal management and tax compliance.")].join(","));

  return lines.join("\r\n");
}

export { printIsolatedDocument };
